using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using NarsiCultCraftReceipt = Content.Shared.RPSX.DarkForces.Narsi.Craft.NarsiCultCraftReceipt;
using NarsiCultCraftReceiptCategoryPrototype = Content.Shared.RPSX.DarkForces.Narsi.Craft.NarsiCultCraftReceiptCategoryPrototype;

namespace Content.Client.RPSX.DarkForces.Narsi.Buildings.Forge.Receipts;

[GenerateTypedNameReferences]
public sealed partial class NarsiReceiptCategory : Control
{
    public NarsiReceiptCategory(NarsiCultCraftReceiptCategoryPrototype prototype, NarsiForgeBoundInterface bui, bool isStateIdle, int runicPlasteelCount, int plasteelCount, int steelCount)
    {
        RobustXamlLoader.Load(this);

        foreach (var data in prototype.Items)
        {
            var item = data.Value;

            var hasEnoughMaterial = IsEnabled(item, runicPlasteelCount, plasteelCount, steelCount);
            var control = new NarsiReceiptControl(item, bui, hasEnoughMaterial, hasEnoughMaterial && isStateIdle);
            Container.AddChild(control);
        }
    }

    private bool IsEnabled(NarsiCultCraftReceipt receipt, int runicPlasteelCount, int plasteelCount, int steelCount)
    {
        return receipt.RequiredMaterial.Id switch
        {
            "RunicPlasteel" => runicPlasteelCount >= receipt.Cost,
            "Plasteel" => plasteelCount >= receipt.Cost,
            "Steel" => steelCount >= receipt.Cost,
            _ => false,
        };
    }
}
