using Content.Client.Stylesheets;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using NarsiCultCraftReceipt = Content.Shared.RPSX.DarkForces.Narsi.Craft.NarsiCultCraftReceipt;

namespace Content.Client.RPSX.DarkForces.Narsi.Buildings.Forge.Receipts;

[GenerateTypedNameReferences]
public sealed partial class NarsiReceiptControl : Control
{
    public NarsiReceiptControl(NarsiCultCraftReceipt prototype, NarsiForgeBoundInterface bui, bool hasEnoughMaterial, bool isEnabled)
    {
        RobustXamlLoader.Load(this);

        Texture.TexturePath = prototype.Icon;
        Name.Text = prototype.Name;
        Description.Text = prototype.Description;

        CreateButton.Text = prototype.ButtonText;
        CreateButton.Disabled = !isEnabled;
        CreateButton.OnPressed += _ => bui.OnCreateButtonPressed(prototype.ItemToSpawn, prototype.RequiredMaterial, prototype.Cost);

        SetupCost(prototype, hasEnoughMaterial);
    }

    private void SetupCost(NarsiCultCraftReceipt prototype, bool hasEnoughMaterial)
    {
        var material = prototype.RequiredMaterial.Id switch
        {
            "RunicPlasteel" => "рунический металл",
            "Plasteel" => "пласталь",
            "Steel" => "сталь",
            _ => throw new System.NotImplementedException(),
        };

        Cost.Text = $"Требуется {material}\n{prototype.Cost} штук";

        if (hasEnoughMaterial)
        {
            Cost.FontColorOverride = StyleNano.GoodGreenFore;
        }
        else
        {
            Cost.FontColorOverride = StyleNano.DangerousRedFore;
        }
    }
}
