using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.RPSX.DarkForces.Narsi.Buildings.Altar.Rituals;

[GenerateTypedNameReferences]
public sealed partial class NarsiRitualControl : Control
{
    public NarsiRitualControl(NarsiRitualsBoundInterface bui, string prototypeID, string name, string description, string requirements, bool isAvailable)
    {
        RobustXamlLoader.Load(this);

        Name.Text = name;
        Description.SetMessage(description);

        if (isAvailable)
        {
            Requirements.SetMessage(FormattedMessage.FromMarkup("[color=#31843E]" + requirements + "[/color]"));
        }
        else
        {
            Requirements.SetMessage(FormattedMessage.FromMarkup("[color=#BB3232]" + requirements + "[/color]"));
        }

        StartRitualButton.OnPressed += _ => bui.OnStartRitualPressed(prototypeID);
        StartRitualButton.Disabled = !isAvailable;
    }
}
