using System.Collections.Generic;
using Content.Shared.RPSX.DarkForces.Narsi.Buildings.Altar.Rituals;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RPSX.DarkForces.Narsi.Buildings.Altar.Rituals;

[GenerateTypedNameReferences]
public sealed partial class NarsiRitualsCategoryControl : Control
{
    public NarsiRitualsCategoryControl(NarsiRitualsBoundInterface bui, List<NarsiRitualUIModel> models)
    {
        RobustXamlLoader.Load(this);

        foreach (var ritual in models)
        {
            var control = new NarsiRitualControl(bui, ritual.PrototypeId, ritual.Name, ritual.Description, ritual.Requirements, ritual.Available);
            Container.AddChild(control);
        }
    }
}
