using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.RPSX.DarkForces.Ratvar.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client.RPSX.DarkForces.Ratvar.Midas;

[GenerateTypedNameReferences]
public sealed partial class RatvarMidasTouchMenu : RadialMenu
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private RatvarMidasTouchBUI _bui;

    public RatvarMidasTouchMenu(RatvarMidasTouchBUI bui)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _bui = bui;
        _spriteSystem = _entManager.System<SpriteSystem>();
    }

    public void Populate(IReadOnlyCollection<string> ids)
    {
        foreach (var id in ids)
        {
            if (!_prototypeManager.TryIndex<RatvarMidasTouchablePrototype>(id, out var prototype))
                continue;

            var button = new RadialMenuTextureButton
            {
                StyleClasses = { "RadialMenuButton" },
                SetSize = new Vector2(64f, 64f),
                ToolTip = prototype.Name
            };

            var texture = new TextureRect
            {
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Texture = _spriteSystem.Frame0(prototype.Icon!),
                TextureScale = new Vector2(2f, 2f)
            };

            button.OnPressed += _ => _bui.Select(id);
            button.AddChild(texture);

            Main.AddChild(button);
        }
    }
}
