- type: jobChatHighlight
  id: SecurityChatHighlight
  triggerWords:
  - СБ
  - Сотрудник безопасности
  - Детектив
  - ГСБ
  - ЯО
  - Синдикат
  - Оружие
  - Враги
  - Чудовище
  - Чудище
  - Тварь
  - Кадет
  - Офицер
  - РЗП
  - БМ
  - Бригмед
  - Бригмедик
  - Пистолет
  - Автомат
  - СРП
  - Закон
  - Нарушают
  - Бриг
  - Подойти
  - Подойдите
  - Убивает
  - Убивают
  - Спасите
  - Помогите
  - Помощь
  - Драка
  - Дерутся
  - Драку
  - Бриг

- type: jobChatHighlight
  id: EngineerHighlight
  triggerWords:
  - Свет
  - Синга
  - Разгерма
  - ДАМ
  - Тесла
  - Инженер
  - Инженеры
  - Почините
  - ЛПК
  - инж
  - инжи
  - инжы
  - СИ
  - Старший инженер
  - атмос
  - воздух
  - дышать
  - кислород
  - атмосферный техник
  - атмосфера

- type: jobChatHighlight
  id: MedicalChatHighlight
  triggerWords:
  - Врач
  - Медик
  - Парамедик
  - Хирург
  - Лечение
  - Вылечите
  - Лечите
  - Помогите
  - Ранен
  - Больница
  - Мед
  - Аптечка
  - Мазь
  - Таблетка
  - Лекарство
  - Ушибов
  - Ушибы
  - Перевязка
  - Вирус
  - Болезнь

- type: jobChatHighlight
  id: ChaplainChatHighlight
  triggerWords:
  - Священник
  - Пастор
  - Проповедь
  - Алтарь
  - Понтифик
  - Скверна
  - Молитва
  - Библия
  - Святость
  - Обряд
  - Демон
  - Экзорцизм
  - Ритуал
  - Секта
  - Культ
  - Исповедь

- type: jobChatHighlight
  id: CommandChatHighlight
  triggerWords:
  - ГП
  - Капитан
  - ОСЩ
  - Стойка
  - Стойке
  - Доступ
  - Выдать
  - Мостик
  - Каюта

- type: jobChatHighlight
  id: CargoChatHighlight
  triggerWords:
  - Карго
  - Снабжение
  - Грузчик
  - Поставка
  - Утиль
  - Утили
  - Заказ
  - Доставка
  - Стойка
  - Стойке
  - Закажите
  - Купите
  - Продайте

- type: jobChatHighlight
  id: ScientistChatHighlight
  triggerWords:
  - Учёный
  - Ученый
  - Аномалия
  - Анома
  - Арт
  - Артефакт
  - Изучите

- type: jobChatHighlight
  id: SAIChatHighlight
  triggerWords:
  - ИИ
  - Открой
  - Заболтируй
  - Наэлектрезуй
  - Преступник
  - Законы

- type: jobChatHighlight
  id: LegalChatHighlight
  triggerWords:
  - АВД
  - Юрист
  - Адвокат
  - Бриг
  - СРП
  - КЗ
  - Помогите
