- type: entity
  id: SuitStorageSecPilot
  parent: SuitStorageBase
  suffix: Security Pilot
  components:
    - type: StorageFill
      contents:
        - id: NitrogenTankFilled
        - id: OxygenTankFilled
        - id: ClothingOuterHardsuitSecurityPilot
        - id: ClothingMaskBreath
