using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.RPSX.GameRules.Pirates;
using Content.Shared.RPSX.GameRules.Pirates.Economics;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.RPSX.GameRules.Pirates.Economics.Shop
{
    [GenerateTypedNameReferences]
    public sealed partial class PirateShopWindow : FancyWindow
    {
        private readonly IEntityManager _entityManager;
        private readonly IPrototypeManager _protoManager;
        private readonly SpriteSystem _spriteSystem;
        private EntityUid _owner;
        public int Balance;

        private readonly EntityQuery<PirateShopComponent> _orderConsoleQuery;

        public event Action<ButtonEventArgs>? OnItemSelected;
        private readonly List<string> _categoryStrings = new();
        private string? _category;

        public List<ProtoId<PirateStuffPrototype>> ProductCatalogue = new();

        public PirateShopWindow(EntityUid owner, IEntityManager entMan, IPrototypeManager protoManager, SpriteSystem spriteSystem)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _entityManager = entMan;
            _protoManager = protoManager;
            _spriteSystem = spriteSystem;
            _owner = owner;

            _orderConsoleQuery = _entityManager.GetEntityQuery<PirateShopComponent>();

            Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

            SearchBar.OnTextChanged += OnSearchBarTextChanged;
            Categories.OnItemSelected += OnCategoryItemSelected;
        }

        private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            SetCategoryText(args.Id);
            PopulateProducts();
        }

        private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
        {
            PopulateProducts();
        }

        private void SetCategoryText(int id)
        {
            _category = id == 0 ? null : _categoryStrings[id];
            Categories.SelectId(id);
        }

        private IEnumerable<PirateStuffPrototype> ProductPrototypes
        {
            get
            {
                foreach (var cargoPrototypeId in ProductCatalogue)
                {
                    var cargoPrototype = _protoManager.Index(cargoPrototypeId);
                    yield return cargoPrototype;
                }
            }
        }

        /// <summary>
        ///     Populates the list of products that will actually be shown, using the current filters.
        /// </summary>
        public void PopulateProducts()
        {
            Products.RemoveAllChildren();
            var products = ProductPrototypes.ToList();
            products.Sort((x, y) =>
                string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase));

            var search = SearchBar.Text.Trim().ToLowerInvariant();
            foreach (var prototype in products)
            {
                // if no search or category
                // else if search
                // else if category and not search
                if (search.Length == 0 && _category == null ||
                    search.Length != 0 && prototype.Name.ToLowerInvariant().Contains(search) ||
                    search.Length != 0 && prototype.Description.ToLowerInvariant().Contains(search) ||
                    search.Length == 0 && _category != null && Loc.GetString(prototype.Category).Equals(_category))
                {
                    var button = new PirateProductRow
                    {
                        Product = prototype,
                        ProductName = { Text = prototype.Name },
                        MainButton = { ToolTip = prototype.Description },
                        PointCost = { Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", prototype.Cost.ToString())) },
                        Icon = { Texture = _spriteSystem.Frame0(prototype.Icon) },
                    };
                    button.MainButton.OnPressed += args =>
                    {
                        OnItemSelected?.Invoke(args);
                    };
                    Products.AddChild(button);
                }
            }
        }

        /// <summary>
        ///     Populates the list of products that will actually be shown, using the current filters.
        /// </summary>
        public void PopulateCategories()
        {
            _categoryStrings.Clear();
            Categories.Clear();

            foreach (var prototype in ProductPrototypes)
            {
                if (!_categoryStrings.Contains(Loc.GetString(prototype.Category)))
                {
                    _categoryStrings.Add(Loc.GetString(prototype.Category));
                }
            }

            _categoryStrings.Sort();

            // Add "All" category at the top of the list
            _categoryStrings.Insert(0, Loc.GetString("cargo-console-menu-populate-categories-all-text"));

            foreach (var str in _categoryStrings)
            {
                Categories.AddItem(str);
            }
        }
        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            PointsLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", Balance));
        }
    }
}
