using Content.RPSX.Shared.GameRules.Pirates.Economics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.RPSX.Client.GameRules.Pirates.Economics.Shop
{
    [GenerateTypedNameReferences]
    public sealed partial class PirateProductRow : PanelContainer
    {
        public PirateStuffPrototype? Product { get; set; }

        public PirateProductRow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
