- type: job
  id: CargoLogistician
  name: job-name-logistician
  description: job-description-logistician
  playTimeTracker: JobCargoLogistician
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 43200 #12 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 108000 #30 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 43200 #12 hrs
    - !type:OverallPlaytimeRequirement
      time: 252000 #70 hrs
  weight: 10
  startingGear: CargoLogisticianGear
  icon: "JobIconCargoLogistician"
  supervisors: job-supervisors-qm
  canBeAntag: false
  chatHighlight: CargoChatHighlight
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: CargoLogisticianGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: CargoLogisticianPDA
    ears: ClothingHeadsetCargoLogistician
    pocket1: AppraisalTool

# Cloths

- type: entity
  parent: ClothingUniformJumpsuitQM
  id: ClothingUniformJumpsuitCargoLogistician
  name: logistician uniform
  description: Stylish uniforms (actually, no).

- type: entity
  parent: ClothingUniformJumpskirtQM
  id: ClothingUniformJumpskirtCargoLogistician
  name: logistician uniform
  description: Stylish uniforms (actually, no).

# Accesuares

- type: entity
  parent: QuartermasterPDA
  id: CargoLogisticianPDA
  name: logistician PDA
  description: A harmonious PDA for the money lover.
  components:
  - type: Pda
    id: CargoLogisticianIDCard
    state: pda-miner

- type: entity
  parent: IDCardStandard
  id: CargoLogisticianIDCard
  name: logistician ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idshaftminer
  - type: PresetIdCard
    job: CargoLogistician

# Head

- type: entity
  parent: ClothingHeadHatQMsoft
  id: ClothingHeadHatCargoLogistician
  name: logistician cap
  description: Best headgear during hot order flow.

- type: entity
  parent: ClothingHeadsetQM
  id: ClothingHeadsetCargoLogistician
  name: logistician headset
  description: A logistician's headset for working with the department and taking direct orders from the command.
  components:
  - type: ContainerFill
    containers:
      key_slots:
      - EncryptionKeyCargo
      - EncryptionKeyCommon
