- type: entity
  name: salt shells crate
  description: Contains 24 rifle cartridges loaded with salt. Civilian use is permitted.
  id: CrateSaltShellsFilled
  parent: CratePlastic
  components:
  - type: StorageFill
    contents:
      - id: ShellShotgunSalt
        amount: 24

- type: entity
  id: CratePepperSprayFilled
  parent: CratePlastic
  name: pepper spray crate
  description: Contains 5 pepper sprays. Civilian use is permitted.
  components:
  - type: StorageFill
    contents:
      - id: PepperSpray
        amount: 5
