using Content.Client.RPSX.Bridges;
using Content.Shared.Body.Part;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RPSX.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class TargetDollUI : UIWidget
{
    private readonly ITargetDollWidgetBridge _targetDollWidget;

    public TargetDollUI()
    {
        RobustXamlLoader.Load(this);
        _targetDollWidget = IoCManager.Resolve<ITargetDollWidgetBridge>();
        _targetDollWidget.InitializeWidget();
    }

    public void SetupWidget()
    {
        _targetDollWidget.SetupWidget(Surface);
    }

    public void Clear()
    {
        _targetDollWidget.Clear();
    }
    public void Hide()
    {
        _targetDollWidget.Hide();
    }

    public void Show()
    {
        _targetDollWidget.Show();
    }

    public void SelectBodyPart(BodyPartType? targetBodyPart, BodyPartSymmetry bodyPartSymmetry)
    {
        _targetDollWidget.SelectBodyPart(targetBodyPart, bodyPartSymmetry);
    }

}
