- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 43200 #12 hrs
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 43200 #12 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 108000 #30 hrs
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 43200 #12 hrs
    - !type:OverallPlaytimeRequirement
      time: 252000 #70 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltSeniorEngineerFilled
    ears: ClothingHeadsetEngineering
    gloves: ClothingHandsGlovesColorYellow
