- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Convex
  #- Core
  - Elkridge
  - Fland
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Plasma
  - Reach
  #- Train
  #- colonial #покашто не будет ее в маппуле ведь сначало я бы хотел узнать о недочетах которые скажут игроки
