- type: gameMapPool
  id: DefaultRPSXMapPool
  maps:
  # RPSX
  - RPSXAstra
  - RPSXAmber
  - RPSXAspid
  - RPSXBarratry
  - RPSXBagel
  - RPSXCluster
  - RPSXSaltern
  - RPSXPacked
  - RPSXPearl
  - RPSXGate
