- type: entity
  id: CCOConsole
  parent: BaseComputer
  name: occ console
  description: CentCom Operator Console. Used to control the station from a distance.
  components:
    - type: CcoConsole
      announcementDisplayName: cco-console-display-name
    - type: ActivatableUI
      key: enum.CcoConsoleInterfaceKey.Key
    - type: UserInterface
      interfaces:
        enum.CcoConsoleInterfaceKey.Key:
          type: CcoConsoleBoundInterface
    - type: AccessReader
      access: [[ "CentCom" ]]
