using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.RPSX.Bank.Prototypes;

namespace Content.Client.RPSX.Bank.PDA.UI.Cartridges
{
    [GenerateTypedNameReferences]
    public sealed partial class ShopProductRow : PanelContainer
    {
        public StoreProductPrototype? Product { get; set; }

        public ShopProductRow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
