- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 # 4h (doctor)
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3h
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  chatHighlight: SecurityChatHighlight
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External

