- type: job
  id: SecurityKnight
  name: job-name-security-knight
  description: job-description-security-knight
  playTimeTracker: JobSecurityKnight
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 43200 #12 hrs
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 28800 #8 hrs
  startingGear: SecurityKnightGear
  icon: "JobIconKnightofStardust"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  chatHighlight: SecurityChatHighlight
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityKnightGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitKnight
    back: ClothingBackpackSecurity_KnightFilled
    shoes: ClothingShoesBootsCombatKnight
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetKnight
    outerClothing: ClothingOuterCoatKnight
    id: Security_KnightPDA
    ears: ClothingHeadsetSecurityKnight
    gloves: ClothingHandsGlovesCombatSecurityKnight
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: MagazinePistol
  InnerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSecurity_KnightFilled
  duffelbag: ClothingBackpackSecurity_KnightFilled
  pocket1: HoloprojectorSecurity
  pocket2: Flash

- type: entity
  categories: [ HideSpawnMenu ]
  parent: ClothingBackpackSecurity_Knight
  id: ClothingBackpackSecurity_KnightFilled
  components:
  - type: StorageFill
    contents:
    - id: BoxSurvivalSecurity
    - id: BoxHoloparasiteKnight
    - id: Flash
    - id: HoloprojectorSecurity
    - id: SecurityWhistle
