- type: gameMapPool
  id: DefaultRPSXMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Cog
  - Core
  - Elkridge
  - Fland
  - Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - CorvaxDelta
  - CorvaxGelta
  - CorvaxIshimura
  - CorvaxSilly
  - CorvaxSplit
  #- Train
