- type: gameMapPool
  id: DefaultRPSXMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Cog
  - Core
  - Elkridge
  - Fland
  - Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - CorvaxDelta
  - CorvaxGelta
  - CorvaxIshimura
  - CorvaxSplit
  # RPSX
  - RPSXAspid
  - RPSXCluster
  - RPSXSaltern
  - RPSXSilly
  - RPSXPacked
  #- Train
